### ISSUE TITLE
[231108] CodeTree - 포탑 부수기

### ISSUE THREAD

**Issue by yoseph0310** [SCSAStudy/Algorithm_Conquer#21]
1. 사이트 : CodeTree
2. 제목 : 포탑 부수기
3. 링크 : [문제링크](https://www.codetree.ai/training-field/frequent-problems/problems/destroy-the-turret?page=1&pageSize=20)

**Comment by yoseph0310** [comment]
문제 내달라고 재촉해도돼요 나또 까먹었네요..

**Comment by dayoungee** [comment]
방금 문제 읽었는데 줠라 괴랄하다,,

**Comment by yoseph0310** [comment]
> 방금 문제 읽었는데 줠라 괴랄하다,,

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
