### ISSUE TITLE
[231129] CodeTree - 예술성

### ISSUE THREAD

**Issue by yoseph0310** [SCSAStudy/Algorithm_Conquer#45]
1. 사이트 : CodeTree
2. 제목 : 예술성
3. 링크 : [문제링크](https://www.codetree.ai/training-field/frequent-problems/problems/artistry/description?page=1&pageSize=20)

**Comment by samsohn0128** [comment]
> 갱장히 지저분한 문제네요 우웩

두근두근

**Comment by samsohn0128** [comment]
> 갱장히 지저분한 문제네요 우웩

어우 이건 너무 더럽다

**Comment by yoseph0310** [comment]
> > 갱장히 지저분한 문제네요 우웩
> 
> 어우 이건 너무 더럽다

ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
