### ISSUE TITLE
[231201] CodeTree - 꼬리잡기놀이

### ISSUE THREAD

**Issue by yoseph0310** [SCSAStudy/Algorithm_Conquer#49]
1. 사이트 : CodeTree 
2. 제목 : 꼬리잡기놀이
3. 링크 : [문제링크](https://www.codetree.ai/training-field/frequent-problems/problems/tail-catch-play/description?page=1&pageSize=20)

**Comment by yoseph0310** [comment]
아,,, 3일 잡았는데 현타오네....

**Comment by slg1119** [comment]
> 아,,, 3일 잡았는데 현타오네....

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
