### ISSUE TITLE
[2311208] BOJ - 미로 탐색

### ISSUE THREAD

**Issue by slg1119** [SCSAStudy/Algorithm_Conquer#57]
1. 사이트 : BOJ
2. 제목 : 미로 탐색
4. 링크 : [문제링크](https://www.acmicpc.net/problem/2178)

**Comment by dayoungee** [comment]
?? 저희 이거 푼 거  같은데 모르고 또 풀었으니 올립니당

**Comment by slg1119** [comment]
> ?? 저희 이거 푼 거 같은데 모르고 또 풀었으니 올립니당

엇 중복이였네요 ㅈㅅㅈㅅ
